parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/crowdsecurity/laurel-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: laurel-logs.log
log_type: laurel
labels: {}
ignore_parsers: false
override_statics: []
