parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/laurel-logs.yaml
scenarios:
- ./scenarios/crowdsecurity/auditd-base64-exec-behavior.yaml
postoverflows:
- ""
log_file: laurel-base64-exec.log
log_type: laurel
labels: {}
ignore_parsers: true
override_statics: []
