parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/a1ad/mikrotik-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: mikrotik-logs.log
log_type: mikrotik
labels: {}
ignore_parsers: false
override_statics: []
