parsers:
- ./parsers/s01-parse/crowdsecurity/supabase-docker-pgsql.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/pgsql-user-enum.yaml
postoverflows:
- ""
log_file: pgsql-user-enum.log
log_type: postgres
labels: {}
ignore_parsers: false
override_statics: []
