parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/a1ad/mikrotik-logs.yaml
scenarios:
- ./scenarios/a1ad/mikrotik-scan-multi_ports.yaml
postoverflows:
- ""
log_file: mikrotik-scan-multi_ports.log
log_type: mikrotik
labels: {}
ignore_parsers: true
override_statics: []
